[package]
version = "0.1.0"
name = "zkVM-program"
edition = "2021"

[workspace]

[dependencies]
sp1-zkvm = "2.0.0"
prover-lib = { path = "../lib" }

# TODO We need the patches/patch_001_mdbx branch, check how to reference the repo directly (merge the branch?).
# ethereum_rust
ethereum_rust-core = { git = "https://github.com/lambdaclass/ethereum_rust", package = "ethereum_rust-core", branch = "patches/patch_001_mdbx", default-features = false }
ethereum_rust-blockchain = { git = "https://github.com/lambdaclass/ethereum_rust", package = "ethereum_rust-blockchain", branch = "patches/patch_001_mdbx", default-features = false }
ethereum_rust-evm = { git = "https://github.com/lambdaclass/ethereum_rust", package = "ethereum_rust-evm", branch = "patches/patch_001_mdbx", default-features = false}
ethereum_rust-rlp = { git = "https://github.com/lambdaclass/ethereum_rust", package = "ethereum_rust-rlp", branch = "patches/patch_001_mdbx", default-features = false }

# revm
revm = { version = "14.0.3", features = [
    "std",
    "serde",
    "kzg-rs",
], default-features = false }

# reth
# This should be a custom error
reth-storage-errors = { git = "https://github.com/paradigmxyz/reth", default-features = false, features = [
    "std",
] }

[patch.crates-io]
sha3 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", branch = "patch-sha3-v0.10.8", package = "sha3" }
crypto-bigint = { git = "https://github.com/sp1-patches/RustCrypto-bigint", branch = "patch-v0.5.5" }
secp256k1 = { git = "https://github.com/sp1-patches/rust-secp256k1", branch = "patch-secp256k1-v0.29.0" }
sha2 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", branch = "patch-v0.10.8", package = "sha2" }
ecdsa-core = { git = "https://github.com/sp1-patches/signatures", package = "ecdsa", branch = "patch-ecdsa-v0.16.9" }
tiny-keccak = { git = "https://github.com/sp1-patches/tiny-keccak", branch = "patch-v2.0.2" }
