version: '3.2'
services:
  reth:
    restart: always
    image: "ghcr.io/paradigmxyz/reth:v1.0.6"
    ports:
      - 127.0.0.1:8545:8545
    volumes:
      - type: bind
        source: ./volumes/reth/data
        target: /rethdata
      - type: bind
        source: ../../test_data/genesis-l1.json
        target: /chaindata

    command: node --dev --datadir /rethdata --http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" --dev.block-time 300ms --chain /chaindata
