participants:
  - el_type: ethrex
    cl_type: lighthouse
    cl_image: sigp/lighthouse:v5.3.0
    validator_count: 32
  - el_type: geth
    cl_type: lighthouse
    cl_image: sigp/lighthouse:v5.3.0
    validator_count: 32

additional_services:
  - assertoor

assertoor_params:
  run_stability_check: false
  run_block_proposal_check: false
  tests:
    - https://raw.githubusercontent.com/ethpandaops/assertoor/refs/heads/master/playbooks/stable/eoa-transactions-test.yaml
