participants:
  - el_type: ethrex
    cl_type: lighthouse
    validator_count: 32
  - el_type: geth
    cl_type: lighthouse
    validator_count: 32

additional_services:
  - assertoor

assertoor_params:
  run_stability_check: false
  run_block_proposal_check: false
  run_transaction_test: true
