[package]
name = "zkvm_interface"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
serde_with = "3.11.0"
thiserror = "1.0.61"

ethrex-core = { path = "../../../../common/", default-features = false }
ethrex-vm = { path = "../../../../vm", default-features = false }
ethrex-rlp = { path = "../../../../common/rlp", default-features = false }
ethrex-storage = { path = "../../../../storage/store", default-features = false }
ethrex-trie = { path = "../../../../storage/trie", default-features = false }

[build-dependencies]
risc0-build = { version = "1.1.2" }

[package.metadata.risc0]
methods = ["guest"]

[features]
default = []
build_zkvm = []

[lib]
path = "./src/lib.rs"

[lints.clippy]
expect_used = "deny"
