[package]
name = "zkvm_interface"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", default-features = false, features = ["derive"] }
thiserror = "1.0.64"

ethrex-storage = { path = "../../../../storage/store" }

# revm
revm = { version = "14.0.3", features = [
    "std",
    "serde",
    "kzg-rs",
], default-features = false }

[build-dependencies]
risc0-build = { version = "1.1.2" }

[package.metadata.risc0]
methods = ["guest"]

[features]
default = []
build_zkvm = []

[lib]
path = "./src/lib.rs"
