[package]
name = "ethrex-levm"
version.workspace = true
edition.workspace = true

[dependencies]
ethrex-core.workspace = true
ethrex-rlp.workspace = true

bytes.workspace = true
sha3 = "0.10.8"
datatest-stable = "0.2.9"
serde = { version = "1.0.203", features = ["derive", "rc"] }
serde_json = { version = "1.0.117" }
walkdir = "2.5.0"
keccak-hash = "0.11.0"
thiserror = "2.0.3"
libsecp256k1 = "0.7.1"

[dev-dependencies]
hex = "0.4.3"
colored = "2.1.0"
spinoff = "0.8.0"

[features]
ethereum_foundation_tests = []

[lints.rust]
unsafe_code = "forbid"
warnings = "warn"
rust_2018_idioms = "warn"

[lints.clippy]
panic = "deny"
unnecessary_cast = "warn"
deref_by_slicing = "warn"
indexing_slicing = "warn"
manual_unwrap_or = "warn"
manual_unwrap_or_default = "warn"
as_conversions = "deny"
unwrap_used = "deny"
expect_used = "deny"

arithmetic_side_effects = "deny"
panicking_overflow_checks = "warn"
manual_saturating_arithmetic = "warn"

[lib]
path = "./src/lib.rs"
