[package]
name = "ethereum_rust_levm"
version.workspace = true
edition.workspace = true

[dependencies]
ethereum_rust-core.workspace = true
ethereum_rust-rlp.workspace = true

bytes.workspace = true
sha3 = "0.10.8"
datatest-stable = "0.2.9"
serde = { version = "1.0.203", features = ["derive", "rc"] }
serde_json = { version = "1.0.117" }
walkdir = "2.5.0"
keccak-hash = "0.11.0"

[dev-dependencies]
hex = "0.4.3"
colored = "2.1.0"
spinoff = "0.8.0"

[features]
ethereum_foundation_tests = []

[lints.rust]
unsafe_code = "forbid"
warnings = "warn"
rust_2018_idioms = "warn"

[lints.clippy]
# as_conversions = "deny"
unwrap_used = "deny"
# expect_used = "deny"
# panic = "deny"
# unnecessary_cast = "warn"
# deref_by_slicing = "warn"
# indexing_slicing = "warn"
# manual_unwrap_or = "warn"
# manual_unwrap_or_default = "warn"
