# example: docker compose -f docker-compose-metrics.yaml -f docker-compose-metrics-l2.override.yaml up
services:
  prometheus:
    image: prom/prometheus
    command: --config.file=/etc/prometheus/prometheus.yaml
    #volumes: defined in the .overrides file
    #ports: defined in the .overrides file
  grafana:
    image: grafana/grafana
    volumes:
      - ./provisioning/grafana_provisioning/dashboards/common_dashboards:/etc/grafana/provisioning/dashboards/common_dashboards
      - ./provisioning/grafana_provisioning/dashboards/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./provisioning/grafana_provisioning/datasources:/etc/grafana/provisioning/datasources
    #ports: defined in the .overrides file
    depends_on:
      - prometheus
