[package]
version = "0.1.0"
name = "ethereum_rust_prover-program"
edition = "2021"

[workspace]

[dependencies]
sp1-zkvm = "2.0.0"

# ethereum_rust
ethereum_rust-vm = { path = "../../../vm", default-features = false }
ethereum_rust-rlp = { path = "../../../common/rlp", default-features = false }
ethereum_rust-core = { path = "../../../common", default-features = false }
ethereum_rust-blockchain = { path = "../../../blockchain", default-features = false }

# revm
revm = { version = "14.0.3", features = [
    "std",
    "serde",
    "kzg-rs",
], default-features = false }

[patch.crates-io]
sha3 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", branch = "patch-sha3-v0.10.8", package = "sha3" }
crypto-bigint = { git = "https://github.com/sp1-patches/RustCrypto-bigint", branch = "patch-v0.5.5" }
secp256k1 = { git = "https://github.com/sp1-patches/rust-secp256k1", branch = "patch-secp256k1-v0.29.0" }
sha2 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", branch = "patch-v0.10.8", package = "sha2" }
ecdsa-core = { git = "https://github.com/sp1-patches/signatures", package = "ecdsa", branch = "patch-ecdsa-v0.16.9" }
tiny-keccak = { git = "https://github.com/sp1-patches/tiny-keccak", branch = "patch-v2.0.2" }
