[package]
name = "revm_comparison"
version = "0.1.0"
edition = "2021"

[lib]
name = "revm_comparison"
path = "src/lib.rs"

[dependencies]
ethrex-levm = { path = "../../" }
hex = "0.4.3"
revm = "9.0.0"
bytes = "1.8.0"

[[bin]]
name = "levm_factorial"
path = "src/levm_factorial.rs"

[[bin]]
name = "revm_factorial"
path = "src/revm_factorial.rs"

[[bin]]
name = "levm_fibonacci"
path = "src/levm_fibonacci.rs"

[[bin]]
name = "revm_fibonacci"
path = "src/revm_fibonacci.rs"
