[package]
name = "ethrex-evm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
revm = { version = "10.0.0", features = ["serde", "std", "serde-json"] }
bytes.workspace = true
ethrex-core.workspace = true
