services:
  ethereum_rust:
    restart: always
    container_name: ethereum_rust_l1
    image: "ethereum_rust_dev"
    build:
      context: ../../../
      dockerfile: ./crates/blockchain/dev/Dockerfile
    ports:
      - 127.0.0.1:8545:8545
    volumes:
      - ../../../test_data/genesis-l1.json:/genesis-l1.json
    command: --network /genesis-l1.json --http.addr 0.0.0.0 --http.port 8545
