[package]
name = "ethereum_rust-evm"
version.workspace = true
edition.workspace = true

[dependencies]
# FIXME: It is necessary not to re-use the workspace definitions.
ethereum_rust-core = { path = "../../common", default-features = false }
ethereum_rust-storage = { path = "../../storage/store", default-features = false }
revm = { version = "14.0.3", features = [
    "serde",
    "std",
    "serde-json",
    "optional_no_base_fee",
    "optional_block_gas_limit",
], default-features = false }
# These dependencies must be kept up to date with the corresponding revm version, otherwise errors may pop up because of trait implementation mismatches
revm-inspectors = { version = "0.8.1" }
revm-primitives = { version = "10.0.0", features = [
    "std",
], default-features = false }
bytes.workspace = true
thiserror.workspace = true
hex.workspace = true
lazy_static.workspace = true

serde.workspace = true
bincode = "1"

[features]
default = ["libmdbx"]
c-kzg = ["revm/c-kzg"]
blst = ["revm/blst"]
no_libmdbx = [
    "ethereum_rust-storage/no_libmdbx",
    "ethereum_rust-core/no_libmdbx",
]
libmdbx = ["ethereum_rust-storage/libmdbx", "ethereum_rust-core/libmdbx"]

[lib]
path = "./evm.rs"
