name: L2 Prover
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]
    paths:
      - "crates/l2/prover/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    # "Lint" is a required check, don't change the name
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        action:
          - command: check
            args: -p ethrex-prover
          - command: clippy
            args: -p ethrex-prover --all-targets --no-default-features
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Add Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: ${{ matrix.action.command }} Command
        run: cargo ${{ matrix.action.command }} ${{ matrix.action.args }}

  test:
    # "Test" is a required check, don't change the name
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Rust toolchain install
        uses: dtolnay/rust-toolchain@stable
      # Use cargo-risczero v1.2.0
      # The risc0-zkvm crate should match this version
      - name: RISC-V zkVM toolchain install
        run: |
          curl -L https://risczero.com/install | bash
          ~/.risc0/bin/rzup install
          rzup extension install cargo-risczero v1.2.0
          rzup extension use cargo-risczero v1.2.0
      - name: Build prover and zkVM
        run: |
          cd crates/l2/prover
          cargo build --release --features build_zkvm
      - name: Test Prover Execution
        run: |
          cd crates/l2/prover
          RUST_LOG=info make perf_test_proving
