name: LEVM EF Tests

on:
  merge_group:
    paths:
      - "crates/vm/levm/**"
  pull_request:
    paths:
      - "crates/vm/levm/**"
    branches: ["*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.79.0

jobs:
  test:
    name: EF Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Rustup toolchain install
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Caching
        uses: Swatinem/rust-cache@v2

      - name: Download EF Tests
        run: |
          cd crates/vm/levm
          make download-ef-tests

      - name: Run tests
        run: |
          cd crates/vm/levm
          make test
