name: Daily LEVM Reporter

on:
  schedule:
    # Every day at midnight
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  RUST_VERSION: 1.80.1

jobs:
  ef-test:
    name: Generate Report for EF Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Rustup toolchain install
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Caching
        uses: Swatinem/rust-cache@v2

      - name: Download EF Tests
        run: |
          cd crates/vm/levm
          make download-evm-ef-tests

      - name: Run tests
        run: |
          cd crates/vm/levm
          make generate-evm-ef-tests-report

      - name: Post results in summary
        run: |
          echo "# Daily LEVM EF Tests Run Report" >> $GITHUB_STEP_SUMMARY
          cat crates/vm/levm/levm_ef_tests_summary_github.txt >> $GITHUB_STEP_SUMMARY

      - name: Post results to ethrex L1 slack channel
        env:
          url: ${{ secrets.ETHREX_L1_SLACK_WEBHOOK }}
        run: sh .github/scripts/publish_levm_ef_tests_summary.sh

      - name: Post results to ethrex L2 slack channel
        env:
          url: ${{ secrets.ETHREX_L2_SLACK_WEBHOOK }}
        run: sh .github/scripts/publish_levm_ef_tests_summary.sh

      - name: Post results to levm slack channel
        env:
          url: ${{ secrets.LEVM_SLACK_WEBHOOK }}
        run: sh .github/scripts/publish_levm_ef_tests_summary.sh
